version: '3'

services:
  ibc0:
    container_name: ibc0
    image: "desmos"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-desmos.log}
    volumes:
      - ./build/ibc/ibc0:/root:Z
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    command: desmos start --home /root --rpc.laddr tcp://0.0.0.0:26657 
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  ibc1:
    container_name: ibc1
    image: "desmos"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-desmos.log}
    volumes:
      - ./build/ibc/ibc1:/root:Z
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    command: desmos start --home /root --rpc.laddr tcp://0.0.0.0:26657 
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  relayer:
    container_name: relayer
    image: relayer
    command: bash setup-tsrelayer.sh
    networks:
      localnet:
        ipv4_address: 192.168.10.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16

        